title: "Michael Borck"
description: "A magazine-style showcase of my professional journey"
baseurl: "/resume-magazine" # the subpath of your site, e.g. /resume-magazine
url: "https://michael-borck.github.io"

theme: null
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Remove logo to prevent the duplicate title showing
# logo: "/assets/images/logo.png" # Site logo for top navigation

# Search functionality
search: true
search_full_content: true

# Enable pagination for magazine-style layout
paginate: 9
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

# Configure custom collections
collections:
  resumes:
    output: true
    permalink: /resumes/:name/
  passions:
    output: true
    permalink: /passions/:name/
  projects:
    output: true
    permalink: /projects/:name/
  teaching:
    output: true
    permalink: /teaching/:name/
  talks:
    output: true
    permalink: /talks/:name/
  research:
    output: true
    permalink: /research/:name/

# Default values
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      related: true
  # _resumes
  - scope:
      path: ""
      type: "resumes"
    values:
      layout: single
      author_profile: false
      read_time: false
      show_date: true
      share: true
      related: true
      classes: wide
      sidebar:
        nav: "resume"
  # _passions
  - scope:
      path: ""
      type: "passions"
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      classes: wide
  # _projects
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      classes: wide
  # _teaching
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      classes: wide
  # _talks
  - scope:
      path: ""
      type: "talks"
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      classes: wide
  # _research
  - scope:
      path: ""
      type: "research"
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      share: true
      classes: wide